language: python
sudo: false
python:
- 2.7
- 3.5
script:
- python setup.py develop
- coverage run setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: Kaniabi
  on:
    tags: true
    repository: zerotk/reraiseit
  password:
    secure: oCEm3CZ2zrvUOQ3wthKTS7vFMCIccU6vO8+pM4GADoHvQrjYWLbMhwreGVW9mVowfjw10/ejBDiAo1ZzZ0a3jAPy4DUjBP+mqH72Ber0nQThO8rejEVBQ+jlDwHrHNAENV7At9yq2nZib3gkOMMzRh7sw2L1tnUFoifqqpBWernYmzLiEgbd7Wm1l6QDLAM/CFOZ6A76puaHlW+aj6ZSop9FWLzZi4qjblOZrZCpmYkl4YdUybFwrIAtfXqx5Sd3DjqYJLwrzL9+mauYWjaNTcaQPVMfepAbIsmCNYbbIo0w7tD4ACN+rq1r7uYQ8Ol1AJ01Jfy+d3R+FvYKN69yDzKGJh1H3kiMjqCnDulRta8MoX7tabL2UIemHbkBCAp3xVCh4lyemOIy25S0LLSsIAiZW506xEYfuijB99O1Bc986Dkg7tc1fG4XZW67Pw7ddFS35vKPEZ/ILbQ88Hs78eHErgp32uOiKcSNMbbWzLKW7m7MdrRUMtF6YlxDTmc01a5tNAEU0ytjtzQ6EMbEs6FbaAcOvDOSFRuNbqBCZ48LtKZSvYUKB6BrNUqJmt7QnUFSHEKVHNtJ9RttX5OWZPMiBmvN6l8n+9t+P6f2kkAuI0MPH8RFQnuG+4r1afDB9YCfkX3LO2rkBhfQLWMxpNynBRmJ6EffKJJE7js0KNs=
